layers:
  - Fonction:
    - AtelierValorisation: /node/*[Fonction = "Atelier Valorisation"]
    - Déchetterie: /node/*[Fonction = "Déchetterie"]
    - Distribution: /node/*[Fonction = "Distribution"]
    - EcoOrganisme: /node/*[Fonction = "Eco-organisme"]
    - EntrepriseRecyclage: /node/*[Fonction = "Entreprise recyclage"]
    - Evènement: /node/*[Fonction = "Evènement"]
    - GisementSpécifique: /node/*[Fonction = "Gisement spécifique"]
    - OpérateurDeTri: /node/*[Fonction = "Opérateur de Tri"]
    - Publication: /node/*[Fonction = "Publication"]
    - Recyclerie: /node/*[Fonction = "Recyclerie"]
    - Ressourcerie: /node/*[Fonction = "Ressourcerie"]
  - Status:
    - Artisan: /node/*[Statut = "Artisan"]
    - Artiste: /node/*[Statut = "Artiste"]
    - Association: /node/*[Statut = "Association"]
    - Auto-entrepreneur: /node/*[Statut = "Auto-entrepreneur"]
    - CommunautéDeCommunes: /node/*[Statut = "Communauté de communes"]
    - Département: /node/*[Statut = "Département"]
    - EntreprisePmePmi: /node/*[Statut = "Entreprise PME-PMI"]
    - EntrepriseInsertion: /node/*[Statut = "Entreprise d'insertion"]
    - EntrepriseNationale: /node/*[Statut = "Entreprise nationale"]
    - EntrepriseTransnationale: /node/*[Statut = "Entreprise transnationale"]
    - EtablissementPublic: /node/*[Statut = "Etablissement public"]
    - Fondation: /node/*[Statut = "Fondation"]
    - Mairie: /node/*[Statut = "Mairie"]
    - Media: /node/*[Statut = "Media"]
    - Région: /node/*[Statut = "Région"]
    - SCIC: /node/*[Statut = "SCIC"]
    - SCOP: /node/*[Statut = "SCOP"]
    - SyndicatMixte: /node/*[Statut = "Syndicat mixte"]
    - UniversitéEcole: /node/*[Statut = "Université - Ecole"]
  - Matières:
    - Mobilier: /node/*[Catégorie = "Mobilier"]
    - Métal: /node/*[Catégorie = "Métal"]
    - Papier/Carton: /node/*[Catégorie = "Papier/Carton"]
    - Textile: /node/*[Catégorie = "Textile"]
    - DEE:
      - Electronique: /node/*[DEE = "Textile"]
      - Electro-ménager-gros-blanc: /node/*[DEE = "Electro-ménager-gros-blanc"]
      - Petit électro-ménager: /node/*[DEE = "Petit électro-ménager"]
      - HI-Fi: /node/*[DEE = "HI-Fi"]
      - Machine-outil: /node/*[DEE = "Machine-outil"]
      - Matériel électroportatif: /node/*[DEE = "Matériel électroportatif"]
      - Matériel d'éclairage: /node/*[DEE = "Matériel d'éclairage"]
    - Gisement spécifique: /node/*[Catégorie = "Gisement spécifique"]
    - Verre: /node/*[Catégorie = "Verre"]
    - Culture:
      - Livre: /node/*[Culture = "Livre"]
      - Magazine: /node/*[Culture = "Magazine"]
      - CD: /node/*[Culture = "CD"]
      - DVD: /node/*[Culture = "DVD"]
      - Jeux-Video: /node/*[Culture = "Jeux-Video"]
      - VHS: /node/*[Culture = "VHS"]
    - Autre:
      - Bibelot: /node/*[autre = "Bibelot"]
      - Jouet: /node/*[autre = "Jouet"]
      - Cadre: /node/*[autre = "Cadre"]
  - Régions:
    - AlsaceChampagneArdenneLorraine: /node/*[starts-with(CodePostal,'08') or starts-with(CodePostal,'10') or starts-with(CodePostal,'51') or starts-with(CodePostal,'52') or starts-with(CodePostal,'54') or starts-with(CodePostal,'55') or starts-with(CodePostal,'57') or starts-with(CodePostal,'67') or starts-with(CodePostal,'68') or starts-with(CodePostal,'88')]
    - NouvelleAquitaine: /node/*[starts-with(CodePostal,'33') or starts-with(CodePostal,'40') or starts-with(CodePostal,'64') or starts-with(CodePostal,'16') or starts-with(CodePostal,'17') or starts-with(CodePostal,'19') or starts-with(CodePostal,'23') or starts-with(CodePostal,'24') or starts-with(CodePostal,'47') or starts-with(CodePostal,'64') or starts-with(CodePostal,'79') or starts-with(CodePostal,'86') or starts-with(CodePostal,'87')]
    - AuvergeRhoneAlpes:  /node/*[starts-with(CodePostal,'01') or starts-with(CodePostal,'03') or starts-with(CodePostal,'07') or starts-with(CodePostal,'15') or starts-with(CodePostal,'26') or starts-with(CodePostal,'38') or starts-with(CodePostal,'42') or starts-with(CodePostal,'43') or starts-with(CodePostal,'63') or starts-with(CodePostal,'69') or starts-with(CodePostal,'73')  or starts-with(CodePostal,'74')]
    - BourgogneFranceComté: /node/*[starts-with(CodePostal,'21') or starts-with(CodePostal,'25') or starts-with(CodePostal,'39') or starts-with(CodePostal,'58') or starts-with(CodePostal,'70') or starts-with(CodePostal,'71') or starts-with(CodePostal,'89') or starts-with(CodePostal,'90')]
    - Bretagne: /node/*[starts-with(CodePostal,'22') or starts-with(CodePostal,'29') or starts-with(CodePostal,'35') or starts-with(CodePostal,'56')]
    - CentreValDeLoire: /node/*[starts-with(CodePostal,'18') or starts-with(CodePostal,'28') or starts-with(CodePostal,'36') or starts-with(CodePostal,'37') or starts-with(CodePostal,'41') or starts-with(CodePostal,'45')]
    - Corse: /node/*[starts-with(CodePostal,'2a') or starts-with(CodePostal,'2b')]
    - Gouadeloupe: /node/*[starts-with(CodePostal,'971')]
    - Guyane: /node/*[starts-with(CodePostal,'973')]
    - IleDeFrance: /node/*[starts-with(CodePostal,'75') or starts-with(CodePostal,'93') or starts-with(CodePostal,'94') or starts-with(CodePostal,'77') or starts-with(CodePostal,'78') or starts-with(CodePostal,'91') or starts-with(CodePostal,'92') or starts-with(CodePostal,'95')]
    - LanguedocRoussillonMidiPy: /node/*[starts-with(CodePostal,'09') or starts-with(CodePostal,'11') or starts-with(CodePostal,'12') or starts-with(CodePostal,'30') or starts-with(CodePostal,'31') or starts-with(CodePostal,'32') or starts-with(CodePostal,'34') or starts-with(CodePostal,'46') or starts-with(CodePostal,'48') or starts-with(CodePostal,'65') or starts-with(CodePostal,'66') or starts-with(CodePostal,'81') or starts-with(CodePostal,'82')]
    - LaRéunion : /node/*[starts-with(CodePostal,'974')]
    - Martinique: /node/*[starts-with(CodePostal,'972')]
    - Mayotte: /node/*[starts-with(CodePostal,'976')]
    - HautDeFrance: /node/*[starts-with(CodePostal,'02') or starts-with(CodePostal,'59') or starts-with(CodePostal,'60') or starts-with(CodePostal,'62') or starts-with(CodePostal,'80')]
    - Normandie: /node/*[starts-with(CodePostal,'14') or starts-with(CodePostal,'27') or starts-with(CodePostal,'50') or starts-with(CodePostal,'61') or starts-with(CodePostal,'76')]
    - PolynésieFrançaise: /node/*[starts-with(CodePostal,'987')]
    - NouvelleCalédonie: /node/*[starts-with(CodePostal,'988')]
    - PaysLoire: /node/*[starts-with(CodePostal,'44') or starts-with(CodePostal,'49') or starts-with(CodePostal,'53') or starts-with(CodePostal,'72') or starts-with(CodePostal,'85')]
    - ProvenceAlpesCotedAzur: /node/*[starts-with(CodePostal,'04') or starts-with(CodePostal,'05') or starts-with(CodePostal,'06') or starts-with(CodePostal,'13') or starts-with(CodePostal,'83') or starts-with(CodePostal,'84')]
  - Links:
    - Relationnels:
      - Editeur: /link/*[TypeRelation = "Editeur"]
      - Emploi: /link/*[TypeRelation = "Emploi"]
      - Entrepôt: /link/*[TypeRelation = "Entrepôt"]
      - Familial: /link/*[TypeRelation = "Familial"]
      - Financement: /link/*[TypeRelation = "Financement"]
      - Gouvernance: /link/*[TypeRelation = "Gouvernance"]
      - Lobbying: /link/*[TypeRelation = "Lobbying"]
      - Organisation: /link/*[TypeRelation = "Organisation"]
      - Partenariat académique: /link/*[TypeRelation = "Partenariat académique"]
      - Partenariat économique: /link/*[TypeRelation = "Partenariat économique"]
      - Partenariat technique: /link/*[TypeRelation = "Partenariat technique"]
      - Prestation: /link/*[TypeRelation = "Prestation"]
      - Membre: /link/*[TypeRelation = "Membre"]
      - Proche: /link/*[TypeRelation = "Proche"]
      - Saisine: /link/*[TypeRelation = "Saisine"]
      - Siège: /link/*[TypeRelation = "Siège"]
      - Sous-tutelle: /link/*[TypeRelation = "Sous-tutelle"]
      - Autre: /link/*[TypeRelation = "Autre"]
    - Flux:
      - Financier: /link/*[TypeFlux = "Financier"]
      - DEA ménager: /link/*[TypeFlux = "DEA ménager"]
      - DEA professionnel: /link/*[TypeFlux = "DEA professionnel"]
      - TLC: /link/*[TypeFlux = "TLC"]
      - DEE ménager: /link/*[TypeFlux = "DEE ménager"]
      - DEE professionnel: /link/*[TypeFlux = "DEE professionnel"]
      - Autres encombrants: /link/*[TypeFlux = "Autres encombrants"]
      - DAE: /link/*[TypeFlux = "DAE"]
      - Autre déchets: /link/*[TypeFlux = "Autre déchets"]


# prévoir de pouvoir explorer aussi bien le graph filtré que le graph complet pour que les xpath qui viennent puissent se faire le graph complet ou affiché selon les besoins.
nodeSizingModes:
  - nombreVoisins: count(/link/*[[target | source = '{id/text()}']])
  - tailleId: string-length(id)
linkSizingModes:
  - tailleNoeudsAssociés: count(/link/*[target | source = '{/node/*[id = '{source/text()}']/id/text()}']) + count(/link/*[target | source = '{/node/*[id = '{target/text()}']/id/text()}'])
  - tailleId: string-length(id)
nodeSize: nombreVoisins
linkSize: tailleNoeudsAssociés
