layers:
  - name: layerName
    filter: xpath
  - layerName: xpath
  - layerName: xpath
  - layerName: xpath
  - layerName: xpath
  - name: layerName
    filter: xpath
    sublayers:
      - layerName: xpath
      - layerName: xpath
      - layerName: xpath
      - layerName: xpath
      - name: layerName
        filter: xpath
        sublayers:
          - layerName: xpath
          - layerName: xpath
          - layerName: xpath
          - layerName: xpath
      - layerName: xpath
      - layerName: xpath
  - layerName: xpath
  - layerName: xpath
  - layerName: xpath
  - layerName: xpath

# calques masqué par défaut :
hideLayers:
  nl4: true
