sudo: required
language: node_js
node_js:
  - node
  - 6
addons:
  firefox: latest
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.de
script:
  - ./node_modules/.bin/karma start --browsers Firefox,Chrome_travis_ci --single-run
