language: node_js
node_js:
  - node
  - 6
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - ./node_modules/.bin/karma start --browsers Chrome_travis_ci --single-run
#  - ./node_modules/.bin/karma start --browsers Firefox,Chrome_travis_ci --single-run
